version: "3.8"
services:
    bot:
        image: groosha/telegram-report-bot:latest
        restart: always
        stop_signal: SIGINT
        env_file:
            - .env
        volumes:
            - /etc/localtime:/etc/localtime:ro
